earnables/earnables/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mainEarnable/', include('mainEarnable.urls')),
    path('admin/', admin.site.urls),
]

earnables/mainEarnable/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:family_id>/', views.get_family, name='detail'),
    path('<int:family_id>/members/', views.get_family_members, name='members'),
    path('<int:family_id>/add_member/', views.add_member, name='add'),
]

earnables/mainEarnable/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Family(models.Model):
    full_name = models.CharField(max_length=200)
    nickname = models.CharField(max_length=200)
    def __str__(self):
        return self.nickname

class FamilyMember(models.Model):
    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    nickname = models.CharField(max_length=200)
    password = models.CharField(max_length=20)
    avatar = models.ImageField(upload_to = 'uploads/avatars')
    isAdmin = models.BooleanField()
    member_age = models.PositiveSmallIntegerField
    def __str__(self):
        return self.nickname

class Earnable(models.Model):
    family_member = models.ForeignKey(FamilyMember, on_delete=models.CASCADE)
    task = models.CharField(max_length=200)
    time_earnable = models.IntegerField(default=0)
    earned_action = models.CharField(max_length=200)
    def __str__(self):
        return self.task    

class ActionHistory(models.Model):
    family_member = models.ForeignKey(FamilyMember, on_delete=models.CASCADE)
    action =  models.ForeignKey(Earnable, on_delete=models.DO_NOTHING)
    FAIL = 0
    SUCCESS = 1
    PENDING = 2
    ERROR = 3
    STATUS = (
        (FAIL, _('Action failed unknown error, try again')),
        (SUCCESS, _('Action succeeded.')),
        (PENDING, _('Action pending.')),
        (ERROR, _('Error # FILL_ME_IN thrown'))
    )
    status = models.PositiveSmallIntegerField(choices=STATUS)
    action_date = models.DateTimeField('date action attempted')
    def get_status(self):
        return self.status
    def __str__(self):
        return self.action 

earnables/mainEarnable/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.http import HttpResponse

# Import models here
from .models import Family

# Create your views here.
def index(request):
    latest_family_list = Family.objects.order_by('full_name')[:5]
    context = {
        'latest_family_list':latest_family_list,
    }
    return render(request, 'main/index.html', context)

def get_family(request, family_id):
    context =  {
        'family_id' : family_id,
    }
    return render(request, 'main/get-family.html', context)

def get_family_members(request, family_id):
    family = get_object_or_404(Family, pk=family_id)
    return render(request, 'main/get_family_members.html', {'family': family})

def add_member(request, family_id):
    return HttpResponse("You're adding a member to Family %s." % family_id)

earnables/mainEarnable/templates/main/get-family.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if family_id %}
        <p>You're looking at Family {{family_id}}</p>
    {% else %}
        <p>No Family found.</p>
    {% endif %}    
</body>
</html>

earnables/mainEarnable/templates/main/get_family_members.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ family.full_name}} - {{family.choice_set.all}}</h1>
    <ul>
    {% for member in family.familymember_set.all %}
        <li>{{ member.full_name }}</li>
    {% endfor %}
    </ul>  
</body>
</html>

earnables/mainEarnable/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% if latest_family_list %}
    <ul>
        {% for family in latest_family_list %}
            <li>{{family.nickname}}<a href="/mainEarnable/{{ family.id }}/">{{ family.full_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Families are available.</p>
{% endif %}    
</body>
</html>